# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: canal_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='canal_data.proto',
  package='grpccommunication',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61nal_data.proto\x12\x11grpccommunication\"q\n\x10ImageDataMessage\x12\x10\n\x08negative\x18\x01 \x01(\x08\x12\x0f\n\x07neutral\x18\x02 \x01(\x08\x12\x10\n\x08positive\x18\x03 \x01(\x08\x12\x14\n\x0c\x62lack_screen\x18\x04 \x01(\x08\x12\x12\n\nimage_name\x18\x05 \x01(\x0c\"A\n\x0cMouseMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06move_x\x18\x02 \x01(\x05\x12\x0e\n\x06move_y\x18\x03 \x01(\x05\"G\n\x12MouseButtonMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06move_x\x18\x02 \x01(\x05\x12\x0e\n\x06move_y\x18\x03 \x01(\x05\"b\n\x11InjuryDataMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tinjury_id\x18\x02 \x01(\x05\x12\x11\n\tplayer_id\x18\x03 \x01(\x05\x12\x14\n\x0cnew_hp_value\x18\x04 \x01(\x05\"K\n\x11QuakeEventMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x11\n\tplayer_id\x18\x03 \x01(\x05\"%\n\x12ServerConfirmation\x12\x0f\n\x07\x63onfirm\x18\x01 \x01(\x0c\x32q\n\x10SendingImageData\x12]\n\rsendImageData\x12#.grpccommunication.ImageDataMessage\x1a%.grpccommunication.ServerConfirmation\"\x00\x32m\n\x10SendingMouseData\x12Y\n\rsendMouseData\x12\x1f.grpccommunication.MouseMessage\x1a%.grpccommunication.ServerConfirmation\"\x00\x32\xd9\x01\n\x11SendingQuakeEvent\x12\x63\n\x12sendQuakeEventData\x12$.grpccommunication.QuakeEventMessage\x1a%.grpccommunication.ServerConfirmation\"\x00\x12_\n\x0esendInjuryData\x12$.grpccommunication.InjuryDataMessage\x1a%.grpccommunication.ServerConfirmation\"\x00\x42:\n\x1cio.grpc.examples.imageviewerB\x12SendingImagesProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_IMAGEDATAMESSAGE = _descriptor.Descriptor(
  name='ImageDataMessage',
  full_name='grpccommunication.ImageDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='negative', full_name='grpccommunication.ImageDataMessage.negative', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neutral', full_name='grpccommunication.ImageDataMessage.neutral', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='positive', full_name='grpccommunication.ImageDataMessage.positive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='black_screen', full_name='grpccommunication.ImageDataMessage.black_screen', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='grpccommunication.ImageDataMessage.image_name', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=152,
)


_MOUSEMESSAGE = _descriptor.Descriptor(
  name='MouseMessage',
  full_name='grpccommunication.MouseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpccommunication.MouseMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_x', full_name='grpccommunication.MouseMessage.move_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='grpccommunication.MouseMessage.move_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=219,
)


_MOUSEBUTTONMESSAGE = _descriptor.Descriptor(
  name='MouseButtonMessage',
  full_name='grpccommunication.MouseButtonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpccommunication.MouseButtonMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_x', full_name='grpccommunication.MouseButtonMessage.move_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='grpccommunication.MouseButtonMessage.move_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=292,
)


_INJURYDATAMESSAGE = _descriptor.Descriptor(
  name='InjuryDataMessage',
  full_name='grpccommunication.InjuryDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpccommunication.InjuryDataMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='injury_id', full_name='grpccommunication.InjuryDataMessage.injury_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='grpccommunication.InjuryDataMessage.player_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_hp_value', full_name='grpccommunication.InjuryDataMessage.new_hp_value', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=392,
)


_QUAKEEVENTMESSAGE = _descriptor.Descriptor(
  name='QuakeEventMessage',
  full_name='grpccommunication.QuakeEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grpccommunication.QuakeEventMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='grpccommunication.QuakeEventMessage.event_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='grpccommunication.QuakeEventMessage.player_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=469,
)


_SERVERCONFIRMATION = _descriptor.Descriptor(
  name='ServerConfirmation',
  full_name='grpccommunication.ServerConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirm', full_name='grpccommunication.ServerConfirmation.confirm', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=508,
)

DESCRIPTOR.message_types_by_name['ImageDataMessage'] = _IMAGEDATAMESSAGE
DESCRIPTOR.message_types_by_name['MouseMessage'] = _MOUSEMESSAGE
DESCRIPTOR.message_types_by_name['MouseButtonMessage'] = _MOUSEBUTTONMESSAGE
DESCRIPTOR.message_types_by_name['InjuryDataMessage'] = _INJURYDATAMESSAGE
DESCRIPTOR.message_types_by_name['QuakeEventMessage'] = _QUAKEEVENTMESSAGE
DESCRIPTOR.message_types_by_name['ServerConfirmation'] = _SERVERCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageDataMessage = _reflection.GeneratedProtocolMessageType('ImageDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEDATAMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:grpccommunication.ImageDataMessage)
  ))
_sym_db.RegisterMessage(ImageDataMessage)

MouseMessage = _reflection.GeneratedProtocolMessageType('MouseMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOUSEMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:grpccommunication.MouseMessage)
  ))
_sym_db.RegisterMessage(MouseMessage)

MouseButtonMessage = _reflection.GeneratedProtocolMessageType('MouseButtonMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOUSEBUTTONMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:grpccommunication.MouseButtonMessage)
  ))
_sym_db.RegisterMessage(MouseButtonMessage)

InjuryDataMessage = _reflection.GeneratedProtocolMessageType('InjuryDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _INJURYDATAMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:grpccommunication.InjuryDataMessage)
  ))
_sym_db.RegisterMessage(InjuryDataMessage)

QuakeEventMessage = _reflection.GeneratedProtocolMessageType('QuakeEventMessage', (_message.Message,), dict(
  DESCRIPTOR = _QUAKEEVENTMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:grpccommunication.QuakeEventMessage)
  ))
_sym_db.RegisterMessage(QuakeEventMessage)

ServerConfirmation = _reflection.GeneratedProtocolMessageType('ServerConfirmation', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCONFIRMATION,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:grpccommunication.ServerConfirmation)
  ))
_sym_db.RegisterMessage(ServerConfirmation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.grpc.examples.imageviewerB\022SendingImagesProtoP\001\242\002\003HLW'))

_SENDINGIMAGEDATA = _descriptor.ServiceDescriptor(
  name='SendingImageData',
  full_name='grpccommunication.SendingImageData',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=510,
  serialized_end=623,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendImageData',
    full_name='grpccommunication.SendingImageData.sendImageData',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATAMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINGIMAGEDATA)

DESCRIPTOR.services_by_name['SendingImageData'] = _SENDINGIMAGEDATA


_SENDINGMOUSEDATA = _descriptor.ServiceDescriptor(
  name='SendingMouseData',
  full_name='grpccommunication.SendingMouseData',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=625,
  serialized_end=734,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMouseData',
    full_name='grpccommunication.SendingMouseData.sendMouseData',
    index=0,
    containing_service=None,
    input_type=_MOUSEMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINGMOUSEDATA)

DESCRIPTOR.services_by_name['SendingMouseData'] = _SENDINGMOUSEDATA


_SENDINGQUAKEEVENT = _descriptor.ServiceDescriptor(
  name='SendingQuakeEvent',
  full_name='grpccommunication.SendingQuakeEvent',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=737,
  serialized_end=954,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendQuakeEventData',
    full_name='grpccommunication.SendingQuakeEvent.sendQuakeEventData',
    index=0,
    containing_service=None,
    input_type=_QUAKEEVENTMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendInjuryData',
    full_name='grpccommunication.SendingQuakeEvent.sendInjuryData',
    index=1,
    containing_service=None,
    input_type=_INJURYDATAMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINGQUAKEEVENT)

DESCRIPTOR.services_by_name['SendingQuakeEvent'] = _SENDINGQUAKEEVENT

# @@protoc_insertion_point(module_scope)
