# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: canal_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='canal_data.proto',
  package='imageviewer',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61nal_data.proto\x12\x0bimageviewer\"q\n\x10ImageDataMessage\x12\x10\n\x08negative\x18\x01 \x01(\x08\x12\x0f\n\x07neutral\x18\x02 \x01(\x08\x12\x10\n\x08positive\x18\x03 \x01(\x08\x12\x14\n\x0c\x62lack_screen\x18\x04 \x01(\x08\x12\x12\n\nimage_name\x18\x05 \x01(\x0c\"A\n\x0cMouseMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06move_x\x18\x02 \x01(\x05\x12\x0e\n\x06move_y\x18\x03 \x01(\x05\"G\n\x12MouseButtonMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06move_x\x18\x02 \x01(\x05\x12\x0e\n\x06move_y\x18\x03 \x01(\x05\"b\n\x11InjuryDataMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x11\n\tinjury_id\x18\x02 \x01(\x05\x12\x11\n\tplayer_id\x18\x03 \x01(\x05\x12\x14\n\x0cnew_hp_value\x18\x04 \x01(\x05\"K\n\x11QuakeEventMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08\x65vent_id\x18\x02 \x01(\x05\x12\x11\n\tplayer_id\x18\x03 \x01(\x05\"%\n\x12ServerConfirmation\x12\x0f\n\x07\x63onfirm\x18\x01 \x01(\x0c\x32\x65\n\x10SendingImageData\x12Q\n\rsendImageData\x12\x1d.imageviewer.ImageDataMessage\x1a\x1f.imageviewer.ServerConfirmation\"\x00\x32\x61\n\x10SendingMouseData\x12M\n\rsendMouseData\x12\x19.imageviewer.MouseMessage\x1a\x1f.imageviewer.ServerConfirmation\"\x00\x32\xc1\x01\n\x11SendingQuakeEvent\x12W\n\x12sendQuakeEventData\x12\x1e.imageviewer.QuakeEventMessage\x1a\x1f.imageviewer.ServerConfirmation\"\x00\x12S\n\x0esendInjuryData\x12\x1e.imageviewer.InjuryDataMessage\x1a\x1f.imageviewer.ServerConfirmation\"\x00\x42:\n\x1cio.grpc.examples.imageviewerB\x12SendingImagesProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_IMAGEDATAMESSAGE = _descriptor.Descriptor(
  name='ImageDataMessage',
  full_name='imageviewer.ImageDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='negative', full_name='imageviewer.ImageDataMessage.negative', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neutral', full_name='imageviewer.ImageDataMessage.neutral', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='positive', full_name='imageviewer.ImageDataMessage.positive', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='black_screen', full_name='imageviewer.ImageDataMessage.black_screen', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='imageviewer.ImageDataMessage.image_name', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=146,
)


_MOUSEMESSAGE = _descriptor.Descriptor(
  name='MouseMessage',
  full_name='imageviewer.MouseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='imageviewer.MouseMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_x', full_name='imageviewer.MouseMessage.move_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='imageviewer.MouseMessage.move_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=213,
)


_MOUSEBUTTONMESSAGE = _descriptor.Descriptor(
  name='MouseButtonMessage',
  full_name='imageviewer.MouseButtonMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='imageviewer.MouseButtonMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_x', full_name='imageviewer.MouseButtonMessage.move_x', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_y', full_name='imageviewer.MouseButtonMessage.move_y', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=286,
)


_INJURYDATAMESSAGE = _descriptor.Descriptor(
  name='InjuryDataMessage',
  full_name='imageviewer.InjuryDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='imageviewer.InjuryDataMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='injury_id', full_name='imageviewer.InjuryDataMessage.injury_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='imageviewer.InjuryDataMessage.player_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='new_hp_value', full_name='imageviewer.InjuryDataMessage.new_hp_value', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=386,
)


_QUAKEEVENTMESSAGE = _descriptor.Descriptor(
  name='QuakeEventMessage',
  full_name='imageviewer.QuakeEventMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='imageviewer.QuakeEventMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_id', full_name='imageviewer.QuakeEventMessage.event_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_id', full_name='imageviewer.QuakeEventMessage.player_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=463,
)


_SERVERCONFIRMATION = _descriptor.Descriptor(
  name='ServerConfirmation',
  full_name='imageviewer.ServerConfirmation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='confirm', full_name='imageviewer.ServerConfirmation.confirm', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=465,
  serialized_end=502,
)

DESCRIPTOR.message_types_by_name['ImageDataMessage'] = _IMAGEDATAMESSAGE
DESCRIPTOR.message_types_by_name['MouseMessage'] = _MOUSEMESSAGE
DESCRIPTOR.message_types_by_name['MouseButtonMessage'] = _MOUSEBUTTONMESSAGE
DESCRIPTOR.message_types_by_name['InjuryDataMessage'] = _INJURYDATAMESSAGE
DESCRIPTOR.message_types_by_name['QuakeEventMessage'] = _QUAKEEVENTMESSAGE
DESCRIPTOR.message_types_by_name['ServerConfirmation'] = _SERVERCONFIRMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageDataMessage = _reflection.GeneratedProtocolMessageType('ImageDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _IMAGEDATAMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:imageviewer.ImageDataMessage)
  ))
_sym_db.RegisterMessage(ImageDataMessage)

MouseMessage = _reflection.GeneratedProtocolMessageType('MouseMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOUSEMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:imageviewer.MouseMessage)
  ))
_sym_db.RegisterMessage(MouseMessage)

MouseButtonMessage = _reflection.GeneratedProtocolMessageType('MouseButtonMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOUSEBUTTONMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:imageviewer.MouseButtonMessage)
  ))
_sym_db.RegisterMessage(MouseButtonMessage)

InjuryDataMessage = _reflection.GeneratedProtocolMessageType('InjuryDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _INJURYDATAMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:imageviewer.InjuryDataMessage)
  ))
_sym_db.RegisterMessage(InjuryDataMessage)

QuakeEventMessage = _reflection.GeneratedProtocolMessageType('QuakeEventMessage', (_message.Message,), dict(
  DESCRIPTOR = _QUAKEEVENTMESSAGE,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:imageviewer.QuakeEventMessage)
  ))
_sym_db.RegisterMessage(QuakeEventMessage)

ServerConfirmation = _reflection.GeneratedProtocolMessageType('ServerConfirmation', (_message.Message,), dict(
  DESCRIPTOR = _SERVERCONFIRMATION,
  __module__ = 'canal_data_pb2'
  # @@protoc_insertion_point(class_scope:imageviewer.ServerConfirmation)
  ))
_sym_db.RegisterMessage(ServerConfirmation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.grpc.examples.imageviewerB\022SendingImagesProtoP\001\242\002\003HLW'))

_SENDINGIMAGEDATA = _descriptor.ServiceDescriptor(
  name='SendingImageData',
  full_name='imageviewer.SendingImageData',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=504,
  serialized_end=605,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendImageData',
    full_name='imageviewer.SendingImageData.sendImageData',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATAMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINGIMAGEDATA)

DESCRIPTOR.services_by_name['SendingImageData'] = _SENDINGIMAGEDATA


_SENDINGMOUSEDATA = _descriptor.ServiceDescriptor(
  name='SendingMouseData',
  full_name='imageviewer.SendingMouseData',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=607,
  serialized_end=704,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendMouseData',
    full_name='imageviewer.SendingMouseData.sendMouseData',
    index=0,
    containing_service=None,
    input_type=_MOUSEMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINGMOUSEDATA)

DESCRIPTOR.services_by_name['SendingMouseData'] = _SENDINGMOUSEDATA


_SENDINGQUAKEEVENT = _descriptor.ServiceDescriptor(
  name='SendingQuakeEvent',
  full_name='imageviewer.SendingQuakeEvent',
  file=DESCRIPTOR,
  index=2,
  options=None,
  serialized_start=707,
  serialized_end=900,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendQuakeEventData',
    full_name='imageviewer.SendingQuakeEvent.sendQuakeEventData',
    index=0,
    containing_service=None,
    input_type=_QUAKEEVENTMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendInjuryData',
    full_name='imageviewer.SendingQuakeEvent.sendInjuryData',
    index=1,
    containing_service=None,
    input_type=_INJURYDATAMESSAGE,
    output_type=_SERVERCONFIRMATION,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SENDINGQUAKEEVENT)

DESCRIPTOR.services_by_name['SendingQuakeEvent'] = _SENDINGQUAKEEVENT

# @@protoc_insertion_point(module_scope)
